name: Run Node.js Script

on:
  push:
    branches:
      - main

jobs:
  edit_message:
    runs-on: ubuntu-latest
    env:
        DISCORD_RULE_WEBHOOK_URL: ${{ secrets.DISCORD_RULE_WEBHOOK_URL }}
        DISCORD_ABOUT_WEBHOOK_URL: ${{ secrets.DISCORD_ABOUT_WEBHOOK_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Node.js script
        run: node build.mjs
